### ISSUE TITLE
Issue when logging in via discord

### ISSUE THREAD

**Issue by MagzR** [jessinthecloud/new-world-company-hub#110]
![image](https://user-images.githubusercontent.com/98782529/153266734-34a3957a-cac5-4936-b66f-b7e51a816d35.png)

Multiple users receive this error when logging in. Some have resolved on their own by mean of blood magic. 

I still receive this error after logging out of the site and discord and then relogging. 

Users affected:

- MagzReloaded#5004
- OmniFlash#0313
- Khaos#5606
-

**Comment by jessinthecloud** [comment]
May be a Cache issue; make sure to forget cache if invalid login?

**Comment by jessinthecloud** [comment]
Force logout on updates from now on
