### ISSUE TITLE
Unable to save loadouts on Dev site

### ISSUE THREAD

**Issue by MagzR** [jessinthecloud/new-world-company-hub#122]
![image](https://user-images.githubusercontent.com/98782529/153666118-4c5626f5-13f7-40df-af63-bf9929274edd.png)

Met with error when trying to enter in loadout.

**Comment by jessinthecloud** [comment]
fixes in 
281d77a6ff8d7ec3e7d10f1d6aa948ffbe62df19
207742676f9c7bf792b225593be3c77494b2a622
